version: "3.7"
services:

  elasticsearch-covid:
    build: elasticsearch/
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 19200:9200
      - 19300:9300
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"

  logstash-covid:
    build: logstash/
    volumes:
      - ./data/la_diaria_v1:/tmp/datos
    ports:
      - 15000:5000
      - 19600:9600
    depends_on:
      - elasticsearch-covid
    environment:
      LS_JAVA_OPTS: "-Xmx500m -Xms500m"
  
  kibana-covid:
    build: kibana/
    ports:
      - 15601:5601
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    depends_on:
      - elasticsearch-covid
  
  corpus-creator-covid:
    build: corpus-creator/
    volumes:
      - type: bind
        source: ./data/la_diaria_v1
        target: /data/la_diaria_v1
  
  qa-covid:
    build: qa/
    environment:
      - FLASK_ENV=development
    ports:
      - 5000:5000
    volumes:
      - ./data:/data
      - type: bind
        source: ./qa
        target: /src
    depends_on:
      - elasticsearch-covid
  
  db-covid:
    image: mdillon/postgis:9.6
    environment:
      - POSTGRES_DB=covid
      - PGUSER=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - LANG=en_US.utf8

  api-covid:
    build: external-api/
    environment:
      - DB_NAME=covid
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_HOST=db-covid
      - DB_PORT=5432
      - SECRET_KEY='secret'
    ports:
      - 8000:8000
    volumes:
      - type: bind
        source: ./external-api
        target: /src
    depends_on:
      - qa-covid
      - db-covid


