name: covid19-qa
channels:
  - defaults
  - pytorch
dependencies:
  - pip:
    - transformers==2.8.0
  - cudatoolkit=10.1.243
  - cudnn=7.6.5
  - pip=20.0
  - python=3.8
  - pytorch=1.4.0
  - nltk=3.4.5
  - scipy=1.4.1
