name: covid19-qa
channels:
  - defaults
  - pytorch
dependencies:
  - pip:
    - git+https://github.com/bryant1410/transformers@a06383e5
  - cudatoolkit=10.1.243
  - cudnn=7.6.5
  - pip=20.0.2
  - python=3.8.1
  - pytorch=1.4.0
