name: CI
on: [pull_request, push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Conda
      uses: s-weigand/setup-conda@v1
      with:
        activate-conda: false
    - name: Install environment
      run: |
        cd qa
        conda env create -f environment.yml
    - name: Reformat the corpus
      run: |
        source activate covid19-qa
        python corpus-creator/corpus_creator.py
    - name: Run QA main
      run: |
        source activate covid19-qa
        cd qa
        python main.py --ignore-es
