name: covid19-qa
channels:
  - defaults
  - pytorch
dependencies:
  - pip:
    - transformers==2.8.0
    - elasticsearch==7.6.0
    - Werkzeug==0.16.1
    - unidecode==1.1.1
    - bcrypt==3.1.7
    - Flask==1.1.2
    - flask-restx==0.2.0
    - flask-accepts==0.16.5
    - Flask-Bcrypt==0.7.1
    - flask-marshmallow==0.11.0
    - Flask-Migrate==2.5.2
    - PyJWT==1.7.1
    - marshmallow==3.4.0
    - gunicorn==20.0.4
    - requests==2.23.0
    - flask_cors==3.0.8
    - marshmallow-dataclass==7.5.0
  - cudatoolkit=10.1.243
  - cudnn=7.6.5
  - numpy=1.18.1
  - pip=20.0
  - python=3.8
  - pytorch=1.4.0
  - scipy=1.4.1
  - seaborn=0.10.0
